In [1]:
import numpy as np 
np.__version__

arr = np.array([1,2,3,4])
print(arr)



[1 2 3 4]


In [3]:
import numpy as np
brr = np.array([[1,2 , 3],[0,7 , 5 ]])
type(brr)
print(brr)

[[1 2 3]
 [0 7 5]]


In [11]:
import numpy as np 
n1 = np.zeros((2,3))
print(n1)

n2 = np.ones((2,4))
print(n2)

# 2 * 5 array of 10 
n1 = np.full((2,5),10)
print(n1)

# n1 = array from 0 to 9
n1 = np.arange(10)
print(n1)

n2 = np.arange(10,20)
print(n2)

n3 = np.arange(30,100,5)
print(n3)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[10 10 10 10 10]
 [10 10 10 10 10]]
[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [18]:
import numpy as np

# random 5 int from between 1 to 100
n1 = np.random.randint(1 , 100 , 5)
print(n1)

# 3 * 3 matrxi of 3 * 3 int from between 0 to 10
n2 = np.random.randint(0 , 10 , (3,3))
n2

[19 58 23 28 16]


array([[9, 5, 3],
       [3, 5, 6],
       [3, 1, 7]], dtype=int32)

In [21]:
import numpy as np

n1 = np.array([[1 , 2 ] , [ 3 , 4 ] , [ 3 , 4 ]])
print(n1.shape)

n1.shape = (2,3)
n1

(3, 2)


array([[1, 2, 3],
       [4, 3, 4]])

In [24]:
import numpy as np

n1 = np.array([10,20,30])
n2 = np.array([4,5,6])

print(np.vstack((n1,n2)))

print(np.hstack((n1,n2)))

print(np.column_stack((n1,n2)))

[[10 20 30]
 [ 4  5  6]]
[10 20 30  4  5  6]
[[10  4]
 [20  5]
 [30  6]]


In [30]:
import numpy as np

n1 = np.array([10,20,30])
n2 = np.array([30,10,60])


print(np.intersect1d(n1,n2))

print(np.setdiff1d(n1,n2))
print(np.setdiff1d(n2,n1))

[10 30]
[20]
[60]


In [33]:
import numpy as np

arr = np.array([[10,20],[30,40]])
arr.shape
print(arr.size)
print(arr.dtype)


4
int64


In [38]:
import numpy as np

n1 = np.array([10,20,30])
n2 = np.array([30,10,60])

sum = np.sum(n1)
print(sum)

sumAllElements = np.sum([n1,n2])
print(sumAllElements)

print(np.sum([n1,n2] , axis= 0))
print(np.sum([n1,n2] , axis= 1))

60
160
[40 30 90]
[ 60 100]


In [42]:
import numpy as np

arr = np.array([[10,20],[30,40]])
print(arr + 1)
print(arr * 2)

print(arr/2)

[[11 21]
 [31 41]]
[[20 40]
 [60 80]]
[[ 5. 10.]
 [15. 20.]]


In [46]:
import numpy as np

# some numpy functions 
arr = np.arange(10,20,2)
print(arr)

print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))

[10 12 14 16 18]
14.0
2.8284271247461903
14.0


In [3]:
import numpy as np

# saving and loading 

n1 = np.array([10,20,30])
np.save('sachin' , n1)

newNe = np.load('sachin.npy')
print(newNe)

[10 20 30]
